/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pckDialog;

/**
 *
 * @author clocal
 */
public class DlgAbout extends javax.swing.JDialog {

    /**
     * Creates new form DlgAide
     */
    public DlgAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitre = new javax.swing.JPanel();
        lblTitre = new javax.swing.JLabel();
        pnlBoutons = new javax.swing.JPanel();
        btnFermer = new javax.swing.JButton();
        pnlImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnlContenu = new javax.swing.JPanel();
        labelNom = new javax.swing.JLabel();
        labelAuteur = new javax.swing.JLabel();
        labelVersion = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        labelDateModif = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblKathy = new javax.swing.JLabel();
        lblSamuel = new javax.swing.JLabel();
        lblWilliam = new javax.swing.JLabel();
        lblJeanClaude = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblDateModif = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("À propos");

        lblTitre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTitre.setText("À propos");
        pnlTitre.add(lblTitre);

        getContentPane().add(pnlTitre, java.awt.BorderLayout.PAGE_START);

        btnFermer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnFermer.setMnemonic('F');
        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        pnlBoutons.add(btnFermer);

        getContentPane().add(pnlBoutons, java.awt.BorderLayout.PAGE_END);

        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\clocal\\Google Drive\\DEV\\Logo\\About.png")); // NOI18N

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addComponent(lblImage)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlImage, java.awt.BorderLayout.LINE_START);

        labelNom.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelNom.setText("Nom :");

        labelAuteur.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelAuteur.setText("Auteur :");

        labelVersion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelVersion.setText("Version :");

        labelDescription.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDescription.setText("Description :");

        labelDateModif.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDateModif.setText("Date modifiée :");

        lblNom.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblNom.setText("Panorama");

        lblKathy.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblKathy.setText("Kathy Landry");

        lblSamuel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblSamuel.setText("Samuel Proulx");

        lblWilliam.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblWilliam.setText("William Thibodeau");

        lblJeanClaude.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblJeanClaude.setText("Jean-Claude Sheehy");

        lblVersion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblVersion.setText("1.2.2");

        lblDateModif.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblDateModif.setText("13/12/2016");

        txaDescription.setColumns(20);
        txaDescription.setRows(5);
        txaDescription.setText("Le logiciel de gestion pédagogique Panorama\ncontient tout les outils pour gérer convenable-\nment un établissement collégial québecois.");
        txaDescription.setEnabled(false);
        jScrollPane1.setViewportView(txaDescription);

        javax.swing.GroupLayout pnlContenuLayout = new javax.swing.GroupLayout(pnlContenu);
        pnlContenu.setLayout(pnlContenuLayout);
        pnlContenuLayout.setHorizontalGroup(
            pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenuLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelVersion)
                    .addComponent(labelDateModif)
                    .addComponent(labelAuteur)
                    .addComponent(labelNom)
                    .addComponent(labelDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(pnlContenuLayout.createSequentialGroup()
                        .addGroup(pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVersion)
                            .addComponent(lblDateModif)
                            .addComponent(lblJeanClaude)
                            .addComponent(lblSamuel)
                            .addComponent(lblWilliam)
                            .addComponent(lblKathy)
                            .addComponent(lblNom))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContenuLayout.setVerticalGroup(
            pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNom)
                    .addComponent(lblNom))
                .addGap(18, 18, 18)
                .addGroup(pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAuteur)
                    .addComponent(lblKathy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWilliam)
                .addGap(7, 7, 7)
                .addComponent(lblSamuel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJeanClaude)
                .addGap(16, 16, 16)
                .addGroup(pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVersion)
                    .addComponent(lblVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDateModif)
                    .addComponent(lblDateModif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlContenu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAbout dialog = new DlgAbout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAuteur;
    private javax.swing.JLabel labelDateModif;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelVersion;
    private javax.swing.JLabel lblDateModif;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblJeanClaude;
    private javax.swing.JLabel lblKathy;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblSamuel;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JLabel lblWilliam;
    private javax.swing.JPanel pnlBoutons;
    private javax.swing.JPanel pnlContenu;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlTitre;
    private javax.swing.JTextArea txaDescription;
    // End of variables declaration//GEN-END:variables
}
